In [20]:
import numpy as np
import pandas as pd

In [21]:
data_path = '../downloaded_data_2019_02_01/planes.csv'
df = pd.read_csv(data_path, parse_dates=['first_flight'])

# Parse dates to datetime
df['first_flight'] = pd.to_datetime(df['first_flight'], errors='coerce', format="%d/%m/%Y") 
df.set_index(np.arange(df.shape[0]))
#df.index.name = 'id'

,plane_name,msn,type,airline,first_flight,registration,status
0,Airbus A220,50001,CS100,Bombardier,2013-09-16,C-FBCS,Active
1,Airbus A220,50002,CS100,Bombardier,2014-01-03,C-GWYD,Active
2,Airbus A220,50003,CS100,Bombardier,2014-03-04,C-GWXJ,Stored
3,Airbus A220,50004,CS100,Bombardier,2014-05-18,C-GWXK,Active
4,Airbus A220,50005,CS100,Bombardier,2013-07-04,C-GWXZ,Active
5,Airbus A220,50006,CS100,Bombardier,2015-10-30,C-FFCO,Active
6,Airbus A220,50010,CS100,Swiss International Airlines,2016-06-16,HB-JBA,Active
7,Airbus A220,50011,CS100,Swiss International Airlines,2016-07-22,HB-JBB,Active
8,Airbus A220,50012,CS100,Swiss International Airlines,2016-09-24,HB-JBC,Active
9,Airbus A220,50013,CS100,Swiss International Airlines,2016-11-06,HB-JBD,Active
10,Airbus A220,50014,CS100,Swiss International Airlines,2016-12-06,HB-JBE,Active
11,Airbus A220,50015,CS100,Swiss International Airlines,2017-02-09,HB-JBF,Active
12,Airbus A220,50016,CS100,Swiss International Airlines,2017-02-26,HB-JBG,Active
13,Airbus A220,50017,CS100,Swiss International Airlines,2017-04-13,HB-JBH,Active
14,Airbus A220,50020,CS100,Delta Air Lines,2018-10-06,N101DU,Active
15,Airbus A220,50021,CS100,Delta Air Lines,2018-12-07,N102DU,Active
16,Airbus A220,50022,CS100,Delta Air Lines,NaT,N103DU,Active
17,Airbus A220,50023,CS100,Delta Air Lines,2018-12-20,N104DU,Active
18,Airbus A220,50029,CS100,Delta Air Lines,NaT,N110DU,On order
19,Airbus A220,55001,CS300,Bombardier,2015-02-27,C-FFDK,Active
20,Airbus A220,55002,CS300,Bombardier,2016-01-20,C-FFDO,Active
21,Airbus A220,55003,CS300,Air Baltic,2016-11-17,YL-CSA,Active
22,Airbus A220,55004,CS300,Air Baltic,2016-12-21,YL-CSB,Active
23,Airbus A220,55005,CS300,Air Baltic,2017-03-13,YL-CSC,Active
24,Airbus A220,55006,CS300,Air Baltic,2017-05-17,YL-CSD,Active
25,Airbus A220,55007,CS300,Air Baltic,2017-06-02,YL-CSE,Active
26,Airbus A220,55008,CS300,Air Baltic,2017-06-27,YL-CSF,Active
27,Airbus A220,55009,CS300,Air Baltic,2017-07-23,YL-CSG,Active
28,Airbus A220,55010,CS300,Swiss International Airlines,NaT,HB-JCA,Active
29,Airbus A220,55011,CS300,Swiss International Airlines,2017-06-15,HB-JCB,Active
...,...,...,...,...,...,...,...
41583,Sukhoi SuperJet 100,95152,100-95LR,Azimuth,2017-12-06,RA-89096,Active
41584,Sukhoi SuperJet 100,95152,100-95LR,Azimuth,2017-12-06,RA-89096,Active
41585,Sukhoi SuperJet 100,95153,100-95LR,Azimuth,2017-12-14,RA-89094,Active
41586,Sukhoi SuperJet 100,95154,100-95LR,Severstal,2017-12-20,RA-89119,Active
41587,Sukhoi SuperJet 100,95155,100-95LR,Azimuth,2018-02-09,RA-89095,Active
41588,Sukhoi SuperJet 100,95156,100-95B,Aeroflot,2018-02-20,RA-89111,Active
41589,Sukhoi SuperJet 100,95157,100-95B,CityJet,2018-03-02,EI-,On order
41590,Sukhoi SuperJet 100,95158,100-95B,Aeroflot,2018-03-15,RA-89112,Active
41591,Sukhoi SuperJet 100,95159,100-95LR,Severstal,2018-03-26,RA-89117,Active
41592,Sukhoi SuperJet 100,95160,100-95B,Aeroflot,2018-04-04,RA-89113,Active
41593,Sukhoi SuperJet 100,95161,100-95B,Aeroflot,2018-04-13,RA-89110,Active
41594,Sukhoi SuperJet 100,95162,100-95B,Aeroflot,2018-04-25,RA-89114,Active
41595,Sukhoi SuperJet 100,95163,100-95LR,CityJet,2018-05-30,EI-,On order
41596,Sukhoi SuperJet 100,95164,100-95B,Interjet,2018-06-18,XA-,On order
41597,Sukhoi SuperJet 100,95165,100-95B,Aeroflot,2018-06-19,RA-89116,Active
41598,Sukhoi SuperJet 100,95166,100-95B,Aeroflot,2018-06-27,RA-89115,Active
41599,Sukhoi SuperJet 100,95167,100-95VIP,NaN,NaT,NaN,On order
41600,Sukhoi SuperJet 100,95168,100-95B,Interjet,2018-07-25,XA-,On order
41601,Sukhoi SuperJet 100,95169,100-95LR,CityJet,2018-07-30,EI-,On order
41602,Sukhoi SuperJet 100,95170,100-95B,Interjet,2018-09-10,XA-,On order
41603,Sukhoi SuperJet 100,95171,100-95B,Interjet,2018-10-01,XA-,On order
41604,Sukhoi SuperJet 100,95172,100-95B,Severstal,2018-09-26,RA-89118,Active
41605,Sukhoi SuperJet 100,95174,100-95B,NaN,NaT,NaN,On order
41606,Sukhoi SuperJet 100,95175,100-95B,NaN,NaT,NaN,On order
41607,Sukhoi SuperJet 100,95176,100-95B,CityJet,2018-11-08,EI-,On order
41608,Sukhoi SuperJet 100,95177,100-95B,NaN,NaT,NaN,On order
41609,Sukhoi SuperJet 100,95178,100-95VIP,NaN,NaT,NaN,On order
41610,Sukhoi SuperJet 100,95179,100-95B,CityJet,2018-12-12,EI,On order
41611,Sukhoi SuperJet 100,97072,100-95B,NaN,NaT,NaN,On order
41612,Sukhoi SuperJet 100,98018,100-95B,NaN,NaT,NaN,On order

In [22]:
df.describe()

,plane_name,msn,type,airline,first_flight,registration,status
count,41613,41613,41612,41511,35106,41511,41612
unique,41,29399,2000,2770,11932,40351,7
top,Boeing 737 Next Gen,101,320-214,American Airlines,1996-08-01 00:00:00,XA-,Active
freq,7496,22,2274,1453,24,26,30711
first,NaN,NaN,NaN,NaN,1967-04-09 00:00:00,NaN,NaN
last,NaN,NaN,NaN,NaN,2019-07-20 00:00:00,NaN,NaN

In [23]:
# Number of A-380
# Companies with most planes

In [24]:
# Oldest plane in DB?
df['plane_age'] = pd.to_datetime('today') - df['first_flight']
df_sorted_by_age = df.sort_values('plane_age', ascending=False)
df_sorted_by_age[df_sorted_by_age['status'] == "Active"]

,plane_name,msn,type,airline,first_flight,registration,status,plane_age
14742,Boeing 737,19594,737-210C,Lignes Aeriennes Congolaises,1968-11-27,9Q-CGQ,Active,18330 days
25369,Boeing 747,19667,747-131,Caspian Airlines,1969-07-13,EP-CQB,Active,18102 days
25371,Boeing 747,19669,747-131,Iran Air Force,1969-12-05,5-8108,Active,17957 days
25370,Boeing 747,19668,747-131,Iran Air Force,1969-12-07,5-8106,Active,17955 days
14869,Boeing 737,20221,737-248,Peruvian Air Force,1970-01-07,FAP 354,Active,17924 days
14880,Boeing 737,20255,737-230C,Jayawijaya Dirgantara,1970-01-23,PK-JRB,Active,17908 days
25380,Boeing 747,19678,747-131,Iran Air Force,1970-09-24,EP-NHT,Active,17664 days
25458,Boeing 747,20080,747-131,Iran Air Force,1970-10-05,5-8103,Active,17653 days
14933,Boeing 737,20483,737-2A8,Indian Air Force,1970-12-23,K3187,Active,17574 days
14934,Boeing 737,20484,737-2A8,Indian Air Force,1971-01-28,K3186,Active,17538 days
38959,McDonnell Douglas DC-10,46601,DC10-10,Federal Express,1971-03-08,N365FE,Active,17499 days
25460,Boeing 747,20082,747-131,Iran Air Force,1971-08-04,EP-NHP,Active,17350 days
38964,McDonnell Douglas DC-10,46606,DC10-10,Federal Express,1971-09-03,N368FE,Active,17320 days
38971,McDonnell Douglas DC-10,46613,DC10-10,Federal Express,1972-05-06,N375FE,Active,17074 days
38926,McDonnell Douglas DC-10,46521,DC10-10,Federal Express,1972-08-03,N550FE,Active,16985 days
14968,Boeing 737,20591,737-2H7C,Interair South African,1972-09-21,ZS-IJJ,Active,16936 days
38973,McDonnell Douglas DC-10,46615,DC10-10,Federal Express,1972-12-01,N381FE,Active,16865 days
38974,McDonnell Douglas DC-10,46616,DC10-10,Federal Express,1973-02-03,N383FE,Active,16801 days
39042,McDonnell Douglas DC-10,46800,DC10-30CF,Project Orbis,1973-03-27,N330AU,Active,16749 days
39044,McDonnell Douglas DC-10,46802,DC10-30CF,Federal Express,1973-06-11,N303FE,Active,16673 days
25558,Boeing 747,20682,747-E-4A,US Air Force,1973-06-13,73-1676,Active,16671 days
39093,McDonnell Douglas DC-10,46930,DC10-10,Federal Express,1973-06-21,N559FE,Active,16663 days
25559,Boeing 747,20683,747-E-4A,US Air Force,1973-09-11,73-1677,Active,16581 days
38718,Lockheed L-1011 TriStar,1067,L-1011-1,Orbital Sciences,1974-02-22,N140SC,Active,16417 days
15031,Boeing 737,20917,737-210C,Bid Air Cargo,1974-02-28,ZS-IAB,Active,16411 days
39101,McDonnell Douglas DC-10,46938,DC10-10,Federal Express,1974-04-15,N560FE,Active,16365 days
38982,McDonnell Douglas DC-10,46624,DC10-10,Federal Express,1974-04-29,N390FE,Active,16351 days
15015,Boeing 737,20836,737-2K2C,Nolinor Aviation,1974-05-09,C-GNLK,Active,16341 days
25560,Boeing 747,20684,747-E-4A,US Air Force,1974-06-06,74-0787,Active,16313 days
39170,McDonnell Douglas DC-10,47807,DC10-10CF,Federal Express,1974-12-17,N68053,Active,16119 days
...,...,...,...,...,...,...,...,...
40625,McDonnell Douglas MD-80/90,53267,MD-88,Delta Air Lines,NaT,N980DL,Active,NaT
40627,McDonnell Douglas MD-80/90,53273,MD-88,Delta Air Lines,NaT,N982DL,Active,NaT
40628,McDonnell Douglas MD-80/90,53274,MD-88,Delta Air Lines,NaT,N983DL,Active,NaT
40635,McDonnell Douglas MD-80/90,53288,MD-83F,Aeronaves TSM,NaT,XA-UZV,Active,NaT
40636,McDonnell Douglas MD-80/90,53289,MD-83,Aeronaves TSM,NaT,XA-UZX,Active,NaT
40637,McDonnell Douglas MD-80/90,53290,MD-83,Aeronaves TSM,NaT,XA-,Active,NaT
40804,McDonnell Douglas MD-80/90,53532,MD-90-30,Delta Air Lines,NaT,N962DN,Active,NaT
40805,McDonnell Douglas MD-80/90,53533,MD-90-30,Delta Air Lines,NaT,N963DN,Active,NaT
40856,McDonnell Douglas MD-80/90,53587,MD-90-30,Delta Air Lines,NaT,N925DN,Active,NaT
40857,McDonnell Douglas MD-80/90,53588,MD-90-30,Delta Air Lines,NaT,N926DH,Active,NaT
40858,McDonnell Douglas MD-80/90,53589,MD-90-30,Delta Air Lines,NaT,N927DN,Active,NaT
40859,McDonnell Douglas MD-80/90,53590,MD-90-30,Delta Air Lines,NaT,N928DN,Active,NaT
40863,McDonnell Douglas MD-80/90,53594,MD-83,American Airlines,NaT,N9624T,Active,NaT
40865,McDonnell Douglas MD-80/90,53596,MD-83,American Airlines,NaT,N9626F,Active,NaT
40866,McDonnell Douglas MD-80/90,53597,MD-83,ATA Airlines Iran,NaT,UR-CPX,Active,NaT
40867,McDonnell Douglas MD-80/90,53598,MD-83,American Airlines,NaT,N9628W,Active,NaT
40868,McDonnell Douglas MD-80/90,53599,MD-83,American Airlines,NaT,N9629H,Active,NaT
41181,Saab 340,215,340B,Air Leap,NaT,SE-LJS,Active,NaT
41183,Saab 340,217,340B,Argentine Gvmt,NaT,T-34,Active,NaT
41256,Saab 340,289,340B,NaN,NaT,NaN,Active,NaT
41339,Saab 340,370,340B,REX Regional Express,NaT,VH-ZLQ,Active,NaT
41340,Saab 340,371,340B,REX Regional Express,NaT,VH-ZLA,Active,NaT
41348,Saab 340,379,340AEW,Swedish Armed Forces,NaT,100003,Active,NaT
41410,Saab 340,440,340B,Hokkaido Air System,NaT,JA02HC,Active,NaT
41412,Saab 340,442,340B,Silver Airways,NaT,N442XJ,Active,NaT
41413,Saab 340,443,340B,Silver Airways,NaT,N343AG,Active,NaT
41414,Saab 340,444,340B,Silver Airways,NaT,N344AG,Active,NaT
41415,Saab 340,445,340B,Silver Airways,NaT,N351AG,Active,NaT
41416,Saab 340,446,340B,Silver Airways,NaT,N346AG,Active,NaT
41511,Sukhoi SuperJet 100,95081,100-95B,Interjet,NaT,XA-VAS,Active,NaT

In [25]:
airlines_list = df['airline'].unique()
df['airline'].value_counts()

American Airlines                                           1453
Delta Air Lines                                             1153
United Airlines                                             1058
Southwest Airlines                                           992
China Southern Airlines                                      668
Federal Express                                              569
China Eastern Airlines                                       567
SkyWest USA                                                  562
Air China                                                    493
Ryanair                                                      457
Lufthansa                                                    396
British Airways                                              365
Air France                                                   321
THY Turkish Airlines                                         313
All Nippon Airways                                           312
Emirates                                                     298
Expressjet                                                   276
Saudi Arabian Airlines                                       274
Aeroflot                                                     273
UPS                                                          271
Alaska Airlines                                              257
Hainan Airlines                                              256
JetBlue Airways                                              255
Endeavor Air                                                 241
Air Canada                                                   241
Qatar Airways                                                236
SAS                                                          229
Indigo                                                       219
Cathay Pacific                                               210
Japan Airlines                                               210
                                                            ...
Reliance                                                       1
LAMIA                                                          1
Mjet                                                           1
Grand Aviation                                                 1
Meadow Lane Air Partners                                       1
Farnair Netherlands                                            1
GTRA Airways                                                   1
Air Comores                                                    1
Sierra American Corp                                           1
Aero Zambia                                                    1
Bulgarian Eagle                                                1
NasJet                                                         1
Skyward                                                        1
Tesis Aviation Enterprise                                      1
Altarello Ltd                                                  1
Solyom Hungarian Airways                                       1
Harwicke Properties                                            1
First Kuwait Corporation                                       1
Religare                                                       1
US Department of Justice-Drug Enforcement Administration       1
Presidential Air                                               1
Larsen Turbo                                                   1
Air Sicilia                                                    1
Turkmenistan Gvmt                                              1
GNG LLC                                                        1
Global Air Tanker                                              1
CBA                                                            1
Türk Hava Kuvvetleri                                           1
Blue Wings                                                     1
International Jet Managment                                    1
Name: airline, Length: 2770, dtype: int64

Empty DataFrame
Columns: [plane_name, msn, type, airline, first_flight, registration, status, plane_age]
Index: []